# permissions for end users to view repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repository-viewer-role
rules:
- apiGroups:
  - cloud.heighliner.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.heighliner.dev
  resources:
  - repositories/status
  verbs:
  - get
